// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPkJ1L7kHUST4w2Eq5jHWRyZ-sfgIu5MY',
    appId: '1:928808832363:web:eb8cf5af4d23ba087f902e',
    messagingSenderId: '928808832363',
    projectId: 'mynotes-flutter-humaid',
    authDomain: 'mynotes-flutter-humaid.firebaseapp.com',
    storageBucket: 'mynotes-flutter-humaid.appspot.com',
    measurementId: 'G-W613RVWB66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJSmfGuPtoKdxdQayRnJrT6XREBVVELk',
    appId: '1:928808832363:android:e323858350355a0c7f902e',
    messagingSenderId: '928808832363',
    projectId: 'mynotes-flutter-humaid',
    storageBucket: 'mynotes-flutter-humaid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWWucajX8N40xigB0_wzL0PLExKuXfQw',
    appId: '1:928808832363:ios:cdbff53e70d104667f902e',
    messagingSenderId: '928808832363',
    projectId: 'mynotes-flutter-humaid',
    storageBucket: 'mynotes-flutter-humaid.appspot.com',
    iosClientId: '928808832363-oejqr8t4o8rfgocdhk1pvsr1a3v7gdoo.apps.googleusercontent.com',
    iosBundleId: 'com.humaidnotes.mynotes',
  );
}
